credit:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://192.168.3.57:3306/data-refill-center-credit?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
lottery:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://192.168.3.57:3306/data-refill-center-lottery?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
jta:
  log-dir: classpath:tx-logs
  transaction-manager-id: txManager